server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA 라우팅
  location / {
    try_files $uri $uri/ /index.html;
  }

  # API 프록시
  location /api/ {
    proxy_pass http://server:5008;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    client_max_body_size 200m;
  }
}
